{
  "is_github_runner": true,
  "container_expose_ports": true,
  "hms_docker_plex_ssl_enabled": true,
  "separate_4k_instances_enable": true,
  "tautulli_include_jbops": true,
  "traefik_security_hardening": true,
  "flaresolverr_enabled": true,
  "custom_scripts_enabled": true,
  "monitoring_scripts_enabled": true,
  "media_avail_script_enabled": true,
  "hmsdocker_expose_ports_enabled_calibre": false,
  "hms_docker_container_map": {
    "traefik": {
      "enabled": true,
      "proxy_host_rule": traefik,
      "directory": true,
      "traefik": true,
      "authentik": false,
      "authentik_provider_type": proxy
    },
    "sonarr": {
      "enabled": true,
      "proxy_host_rule": sonarr,
      "directory": true,
      "traefik": true,
      "authentik": false,
      "authentik_provider_type": proxy,
      "expose_to_public": false,
      "homepage": true,
      "homepage_stats": false
    },
    "radarr": {
      "enabled": true,
      "proxy_host_rule": radarr,
      "directory": true,
      "traefik": true,
      "authentik": false,
      "authentik_provider_type": proxy,
      "expose_to_public": false,
      "homepage": true,
      "homepage_stats": false
    },
    "bazarr": {
      "enabled": true,
      "proxy_host_rule": bazarr,
      "directory": true,
      "traefik": true,
      "authentik": false,
      "authentik_provider_type": proxy,
      "expose_to_public": false,
      "homepage": true,
      "homepage_stats": false
    },
    "transmission": {
      "enabled": false,
      "proxy_host_rule": transmission,
      "directory": true,
      "traefik": true,
      "authentik": false,
      "authentik_provider_type": proxy,
      "expose_to_public": false,
      "homepage": true,
      "homepage_stats": true
    },
    "portainer": {
      "enabled": true,
      "proxy_host_rule": portainer,
      "directory": true,
      "traefik": true,
      "authentik": false,
      "authentik_provider_type": oauth2,
      "expose_to_public": false,
      "homepage": true,
      "homepage_stats": false
    },
    "overseerr": {
      "enabled": true,
      "proxy_host_rule": overseerr,
      "directory": true,
      "traefik": true,
      "authentik": false,
      "authentik_provider_type": proxy,
      "expose_to_public": false,
      "homepage": true,
      "homepage_stats": false
    },
    "prowlarr": {
      "enabled": true,
      "proxy_host_rule": prowlarr,
      "directory": true,
      "traefik": true,
      "authentik": false,
      "authentik_provider_type": proxy,
      "expose_to_public": false,
      "homepage": true,
      "homepage_stats": false
    },
    "requestrr": {
      "enabled": true,
      "proxy_host_rule": requestrr,
      "directory": true,
      "traefik": true,
      "authentik": false,
      "authentik_provider_type": proxy,
      "expose_to_public": false,
      "homepage": true,
      "homepage_stats": false
    },
    "plex": {
      "enabled": true,
      "proxy_host_rule": plex,
      "directory": true,
      "traefik": true,
      "authentik": false,
      "authentik_provider_type": proxy,
      "expose_to_public": false,
      "homepage": true,
      "homepage_stats": true
    },
    "tautulli": {
      "enabled": true,
      "proxy_host_rule": tautulli,
      "directory": true,
      "traefik": true,
      "authentik": false,
      "authentik_provider_type": proxy,
      "expose_to_public": false,
      "homepage": true,
      "homepage_stats": false
    },
    "nzbget": {
      "enabled": true,
      "proxy_host_rule": nzbget,
      "directory": true,
      "traefik": true,
      "authentik": false,
      "authentik_provider_type": proxy,
      "expose_to_public": false,
      "homepage": true,
      "homepage_stats": true
    },
    "sabnzbd": {
      "enabled": true,
      "proxy_host_rule": sabnzbd,
      "directory": true,
      "traefik": true,
      "authentik": false,
      "authentik_provider_type": proxy,
      "expose_to_public": false,
      "homepage": true,
      "homepage_stats": true
    },
    "authentik": {
      "enabled": true,
      "proxy_host_rule": "authentik",
      "directory": true,
      "traefik": true,
      "authentik": false,
      "authentik_provider_type": proxy,
      "expose_to_public": false,
      "homepage": true,
      "homepage_stats": false
    },
    "tdarr": {
      "enabled": true,
      "proxy_host_rule": tdarr,
      "directory": true,
      "traefik": true,
      "authentik": false,
      "authentik_provider_type": proxy,
      "expose_to_public": false,
      "homepage": true,
      "homepage_stats": false
    },
    "homepage": {
      "enabled": true,
      "proxy_host_rule": "homepage",
      "directory": true,
      "traefik": true,
      "authentik": false,
      "authentik_provider_type": proxy,
      "expose_to_public": false,
      "homepage": true,
      "homepage_stats": false
    },
    "uptimekuma": {
      "enabled": true,
      "proxy_host_rule": uptime-kuma,
      "directory": true,
      "traefik": true,
      "authentik": false,
      "authentik_provider_type": proxy,
      "expose_to_public": false
    },
    "heimdall": {
      "enabled": true,
      "proxy_host_rule": heimdall,
      "directory": true,
      "traefik": true,
      "authentik": false,
      "authentik_provider_type": proxy,
      "expose_to_public": false
    },
    "readarr": {
      "enabled": true,
      "proxy_host_rule": readarr,
      "directory": true,
      "traefik": true,
      "authentik": false,
      "authentik_provider_type": proxy,
      "expose_to_public": false
    },
    "kavita": {
      "enabled": true,
      "proxy_host_rule": kavita,
      "directory": true,
      "traefik": true,
      "authentik": false,
      "authentik_provider_type": proxy,
      "expose_to_public": false
    },
    "calibre": {
      "enabled": true,
      "proxy_host_rule": calibre,
      "directory": true,
      "traefik": true,
      "authentik": false,
      "authentik_provider_type": proxy,
      "expose_to_public": false
    },
    "jellyfin": {
      "enabled": true,
      "proxy_host_rule": jellyfin,
      "directory": true,
      "traefik": true,
      "authentik": false,
      "authentik_provider_type": proxy,
      "expose_to_public": false,
      "homepage": true,
      "homepage_stats": false
    },
    "emby": {
      "enabled": true,
      "proxy_host_rule": emby,
      "directory": true,
      "traefik": true,
      "authentik": false,
      "authentik_provider_type": proxy,
      "expose_to_public": false,
      "homepage": true,
      "homepage_stats": false
    },
    "maintainerr": {
      "enabled": true,
      "proxy_host_rule": "maintainerr",
      "directory": true,
      "traefik": true,
      "authentik": false,
      "authentik_provider_type": "proxy",
      "expose_to_public": false,
    },
    "unpackerr": {
      "enabled": true,
      "proxy_host_rule": "unpackerr",
      "directory": true,
      "traefik": true,
      "authentik": false,
      "authentik_provider_type": "proxy",
      "expose_to_public": false,
    },
    "lidarr": {
      "enabled": true,
      "proxy_host_rule": "lidarr",
      "directory": true,
      "traefik": true,
      "authentik": false,
      "authentik_provider_type": "proxy",
      "expose_to_public": false,
      "homepage": true,
      "homepage_stats": false
    },
    "autobrr": {
      "enabled": true,
      "proxy_host_rule": "autobrr",
      "directory": true,
      "traefik": true,
      "authentik": false,
      "authentik_provider_type": "proxy",
      "expose_to_public": false,
      "homepage": true,
      "homepage_stats": false
    },
    "speedtest-tracker": {
      "enabled": true,
      "proxy_host_rule": "speedtest",
      "directory": true,
      "traefik": true,
      "authentik": false,
      "authentik_provider_type": "proxy",
      "expose_to_public": false,
    },
    "recyclarr": {
      "enabled": true,
      "directory": true,
    },
    "tinymediamanager": {
      "enabled": true,
      "proxy_host_rule": "tmm",
      "directory": true,
      "traefik": true,
      "authentik": false,
      "authentik_provider_type": "proxy",
      "expose_to_public": false,
    },
    "pasta": {
      "enabled": true,
      "proxy_host_rule": "pasta",
      "directory": true,
      "traefik": true,
      "authentik": false,
      "authentik_provider_type": "proxy",
      "expose_to_public": false,
    },
    "netdata": {
      "enabled": true
    },
  }
}
