---
- hosts: all
  become: yes
  gather_facts: yes
  vars:
    hmsd_current_version: 1.4
    hmsd_version_file: "{{ hms_docker_data_path }}/.hmsd-version"
    regex: '[^A-Za-z0-9._-]'
    replace: '_'
    arr_apikey: '(?<=\<ApiKey\>)\w*(?=\<\/ApiKey\>)'
    

  roles:
    - galaxy-roles/geerlingguy.docker

  tasks:
  - name: Ensure Nvidia GPU role if enabled
    ansible.builtin.import_role:
      name: gpu
    when: enable_nvidia_gpu is defined and enable_nvidia_gpu

  - name: Ensure HMS-Docker role
    ansible.builtin.import_role:
      name: hmsdocker

  - name: Verify all Traefik endpoints are accessible
    ansible.builtin.uri:
      url: http://{{ item.value.proxy_host_rule }}.{{ hms_docker_domain }}
      status_code: 200,302,401,403
      validate_certs: no
    with_dict:
      - "{{ hms_docker_container_map }}"
    when:
      - item.value.traefik is defined and item.value.traefik
      - item.value.enabled is defined and item.value.enabled
      - hmsdocker_container_enabled_traefik
      - traefik_verify_endpoints is defined and traefik_verify_endpoints
