---
- name: Ensure authentik secret key file
  ansible.builtin.template:
    src: authentik_secret.j2
    dest: "{{ authentik_key_path }}"
    mode: 0600
    owner: root
    group: root
    backup: yes
    force: no
  register: authentik_key_template_output
  no_log: true
  vars:
    key: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_letters', 'digits'], length=50) }}"

- name: Ensure authentik postgres password file
  ansible.builtin.template:
    src: authentik_secret.j2
    dest: "{{ authentik_pgpass_path }}"
    mode: 0600
    owner: root
    group: root
    backup: yes
    force: no
  register: authentik_pgpass_template_output
  no_log: true
  vars:
    key: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_letters', 'digits'], length=50) }}"

- name: Slurp authentik secret key data
  ansible.builtin.slurp:
    src: "{{ authentik_key_template_output.dest }}"
  register: slurped_key_data
  check_mode: false
  when: authentik_key_template_output.dest is defined
  no_log: true

- name: Slurp authentik postgres password data
  ansible.builtin.slurp:
    src: "{{ authentik_pgpass_template_output.dest }}"
  register: slurped_pg_pass_data
  check_mode: false
  when: authentik_pgpass_template_output.dest is defined
  no_log: true

- name: Ensure Outposts directory
  ansible.builtin.file:
    path: "{{ hms_docker_apps_path }}/authentik/outposts"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Ensure authentik Outpost configs
  ansible.builtin.template:
    src: authentik_outpost.j2
    dest: "{{ hms_docker_apps_path }}/authentik/outposts/authentik-{{ item.key }}.outpost.yml"
    mode: 0644
  with_dict: "{{ hms_docker_container_map }}"
  when: 
    - item.value.enabled 
    - item.value.authentik is defined and item.value.authentik
    - item.value.authentik_provider_type is defined and item.value.authentik_provider_type == 'proxy'

- name: Ensure authentik Outpost configs for static traefik configs
  ansible.builtin.template:
    src: authentik_outpost_ext_host.j2
    dest: "{{ hms_docker_apps_path }}/authentik/outposts/authentik-{{ item.friendly_name | map('regex_replace', regex, replace) | list | join }}.outpost.yml"
    mode: 0644
  with_items: "{{ traefik_ext_hosts_list }}"
  when: 
    - item.enabled 
    - item.authentik is defined and item.authentik
    - item.authentik_provider_type is defined and item.authentik_provider_type == 'proxy'

- name: Ensure authentik Outpost configs for 4K containers
  ansible.builtin.template:
    src: authentik_outpost_4k.j2
    dest: "{{ hms_docker_apps_path }}/authentik/outposts/authentik-{{ item.key }}-{{ separate_4k_instances_suffix }}.outpost.yml"
    mode: 0644
  with_dict: "{{ hms_docker_container_map }}"
  when: 
    - item.value.enabled 
    - item.value.authentik is defined and item.value.authentik
    - item.key == 'sonarr' or item.key == 'radarr'
    - item.value.authentik_provider_type is defined and item.value.authentik_provider_type == 'proxy'
    - separate_4k_instances_enable is defined and separate_4k_instances_enable
