---
- name: restart traefik
  community.docker.docker_container:
    name: traefik
    state: started
    restart: yes
  when: not traefik_certs_dir.changed

- name: restart sabnzbd
  community.docker.docker_container:
    name: sabnzbd
    state: started
    restart: yes
